{% set version = "20.4.24" %}
{% set name = "ecl" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tgz
  url: https://common-lisp.net/project/ecl/static/files/release/{{ name }}-{{ version }}.tgz
  sha256: 670838edf258a936b522fdb620da336de7e575aa0d27e34841727252726d0f07

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - libtool
    - make
  host:
    - gmp
    - readline
    - bdw-gc
  run:
    - gmp
    - readline
    - {{ pin_compatible('bdw-gc') }}

test:
  commands:
    - test -f ${PREFIX}/include/{{ name }}/{{ name }}.h
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so     # [linux]
    - ecl --version

about:
  home: https://common-lisp.net/project/ecl
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: ECL (Embeddable Common-Lisp) is an interpreter of the Common-Lisp language.
  doc_url: https://common-lisp.net/project/ecl/static/ecldoc/
  dev_url: https://gitlab.com/embeddable-common-lisp/ecl

extra:
  recipe-maintainers:
    - isuruf
    - embray
    - saraedum
