{% set version = "24.5.10" %}
{% set name = "ecl" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://common-lisp.net/project/ecl/static/files/release/{{ name }}-{{ version }}.tgz
  sha256: e4ea65bb1861e0e495386bfa8bc673bd014e96d3cf9d91e9038f91435cbe622b
  patches:
    # from https://github.com/sagemath/sage/blob/master/build/pkgs/ecl/patches/write_error.patch
    - write_error.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - libtool
    - make
    - texinfo
    - sed
    # We (typically) need a compatible version of ecl when cross-compiling ecl.
    # On a major upgrade, this cannot be satisfied. When this fails, we merge
    # the PR that builds the native ecl and then restart the CI once the native
    # versions are uploaded.
    - ecl 23.*  # [build_platform != target_platform]
  host:
    - gmp
    - readline
    - bdw-gc
  run:
    - gmp
    - readline
    - {{ pin_compatible('bdw-gc') }}

test:
  commands:
    - test -f ${PREFIX}/include/{{ name }}/{{ name }}.h
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so     # [linux]
    - ecl --version

about:
  home: https://common-lisp.net/project/ecl
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: ECL (Embeddable Common-Lisp) is an interpreter of the Common-Lisp language.
  doc_url: https://common-lisp.net/project/ecl/static/ecldoc/
  dev_url: https://gitlab.com/embeddable-common-lisp/ecl

extra:
  recipe-maintainers:
    - isuruf
    - embray
    - saraedum
