{% set version = "16.1.2" %}
{% set name = "ecl" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tgz
  url: https://common-lisp.net/project/ecl/static/files/release/{{ name }}-{{ version }}.tgz
  sha256: 2d482b1a0a4fbd5d881434517032279d808cb6405e22dd91ef6d733534464b99
  patches:
    # Patch from https://github.com/sagemath/sage
    # Ignore write errors to stderr to avoid an infinite loop
    - write_error.patch
    # https://gitlab.com/embeddable-common-lisp/ecl/commit/6be9cb9dee2fc8df59604aa28413625898e70945.patch
    - fix_osx_runtime_path.patch
    # Backport changes from upstream to the atan implementation--this fixes a
    # bug that turns up in maxima.
    - atan.patch
    # Backport from upstream to "Prevent busy loop during ECL interpreter
    # shutdown on Cygwin" (for Sage)
    - 47b1e98272b6.patch
    # Backport to work around https://trac.sagemath.org/ticket/23011 in Sage
    - 0c9e67345c36.patch
    # Do not require .git to be present
    - tags.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - libtool
  host:
    - gmp
    - readline
    - bdw-gc
  run:
    - gmp
    - readline
    - {{ pin_compatible('bdw-gc') }}

test:
  commands:
    - test -f ${PREFIX}/include/{{ name }}/{{ name }}.h
    - test -f ${PREFIX}/lib/lib{{ name }}.dylib  # [osx]
    - test -f ${PREFIX}/lib/lib{{ name }}.so     # [linux]
    - ecl --version

about:
  home: https://common-lisp.net/project/ecl
  license: GPLv2+
  license_file: COPYING
  summary: ECL (Embeddable Common-Lisp) is an interpreter of the Common-Lisp language.
  doc_url: https://common-lisp.net/project/ecl/static/ecldoc/
  dev_url: https://gitlab.com/embeddable-common-lisp/ecl

extra:
  recipe-maintainers:
    - isuruf
    - embray
    - saraedum
