appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: default, linux_ppc64le: default}
travis:
  secure: {BINSTAR_TOKEN: GRwB9VfhPDmpV1d8jS7UvvMWAzJ4whl/YXlTC9ulcB9Uv6Kb3V5tIo52gLMfXCUckKrR9iePErjMOqCAtoWCVAn2/bQvWBzLh2Dj7fTUl1UwLBDcNGU+a6Lkgev/hsgUlTanJFWnIcR1tTwDS/QjUxJxhFgDJySUFxh/ZWOhMqaB9nLcKifgLanzjGk4iSGGrrfSboNqi5aPmq125/OBReTa+orDEbodxq6o3EDhQHCNZT3Og0x9Hs+fbh4DOocaEQ5ShsYfEzugFmrVrh5/vjamFSLDFAAPNmsMs+mKDSg2NeMqo9DI0MIn1T5VxTDd4e0u5DvLp0vAvPYYmaRqOwY8FmjdFN8DrtnWdu/K9pF0BH5ozaQ6r8ZaglnFwnEEztp8qSCHYJ0BS0UX/u9l+f8QL2cz1acvAzOBGJuX39tkjFuB0zVcNGa+N6TRqOUhHzSL40fwnyomCLRiBxE/9cmRMmeDZFvaoE/gn8nmFX+SiSP2v7gCIr3jjx+84D/yNVXoKO1CtadZ6644GKeq0r6xT8ylXQ/xQaOWlA99JaIxwRbx6XyMESthTF4ntuF1YPXiurnHhoHT7ar8mgiQnjY7Oiq6cZ1IlfGrivx6OrTyPCCdwOm/hLAl2d1Zl5QHgtHM5IjtPDwzOVflm0AKZjEej7ChrvdjJDLKIfgzegU=}
conda_forge_output_validation: true
